# fly.toml app configuration file generated for pdh4869-github-io on 2024-02-13T17:34:30+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pdh4869-github-io'
primary_region = 'nrt'

[build]
  #image = "nginx"
  #image = "dhparkdocker/blog-1:0.1.0"
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
